### ISSUE TITLE
微信公众号使用报错

### ISSUE THREAD

**Issue by autherlj** [haikerapples/timetask#10]
cow版本1.3.3
插件版本：8432efa 路由消息增加try catch容错处理
配置信息：
$ cat config.json
{
  "command_prefix": "&time",
  "debug": false,
  "time_check_rate": 1,
  "move_historyTask_time": "04:00:00",
  "is_open_extension_function": true,
  "extension_function":
  [
    {
      "key_word": "早报",
      "func_command_prefix":"&tool "
    },
    {
      "key_word": "点歌",
      "func_command_prefix": "&"
    },
    {
      "key_word": "搜索",
      "func_command_prefix": "&tool google "
    },
    {
      "key_word": "GPT",
      "func_command_prefix": "GPT"
    }
  ]
}

报错信息：
[INFO][2023-07-25 14:25:12][active_reply.py:44] - [wechatmp] 127.0.0.1:54916 Receive post query omj396omoXzhqTvFRLkgDjiO7Z9c 24198795077273891: &time 每天 14:21 早报
127.0.0.1:54916 - - [25/Jul/2023 14:25:12] "HTTP/1.1 POST /wx" - 200 OK
[timetask] 捕获到定时任务:&time 每天 14:21 早报
[ERROR][2023-07-25 14:25:12][wechatmp_channel.py:238] - [wechatmp] Fail to generate reply to user, msgId=24198795077273891, exception=sequence item 3: expected str instance, NoneType found
Traceback (most recent call last):
  File "/usr/local/python3.9.16/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/chatgpt-projects/chatgpt-on-wechat/channel/chat_channel.py", line 146, in _handle
    reply = self._generate_reply(context)
  File "/opt/chatgpt-projects/chatgpt-on-wechat/channel/chat_channel.py", line 156, in _generate_reply
    e_context = PluginManager().emit_event(
  File "/opt/chatgpt-projects/chatgpt-on-wechat/plugins/plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "/opt/chatgpt-projects/chatgpt-on-wechat/plugins/timetask/timetask.py", line 71, in on_handle_context
    self.deal_timeTask(content, e_context)
  File "/opt/chatgpt-projects/chatgpt-on-wechat/plugins/timetask/timetask.py", line 83, in deal_timeTask
    self.add_timeTask(content, e_context)
  File "/opt/chatgpt-projects/chatgpt-on-wechat/plugins/timetask/timetask.py", line 186, in add_timeTask
    taskModel = TimeTaskModel(taskInfo, msg, True)
  File "/opt/chatgpt-projects/chatgpt-on-wechat/plugins/timetask/Tool.py", line 450, in __init__
    temp_content='_'.join(new_tuple)
TypeError: sequence item 3: expected str instance, NoneType found

**Comment by haikerapples** [comment]
使用最新版试试

**Comment by haikerapples** [comment]
最新的2.5版本试试，应该OK了
