### ISSUE TITLE
运行一天后无法使用，提示Bad magic number for central directory

### ISSUE THREAD

**Issue by gaohuaigh** [haikerapples/timetask#31]
环境、依赖安装之类都没问题，昨天一切正常工作，今天无法使用，日志如下：

[timetask] 捕获到定时任务:$t 任务列表
[ERROR][2023-12-03 10:10:07][chat_channel.py:299] - Worker return exception: Bad magic number for central directory
Traceback (most recent call last):
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\chatgpt-on-wechat-master-2\channel\chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
  File "E:\chatgpt-on-wechat-master-2\channel\chat_channel.py", line 178, in _generate_reply
    e_context = PluginManager().emit_event(
  File "E:\chatgpt-on-wechat-master-2\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "E:\chatgpt-on-wechat-master-2\plugins\timetask\timetask.py", line 76, in on_handle_context
    self.deal_timeTask(content, e_context)
  File "E:\chatgpt-on-wechat-master-2\plugins\timetask\timetask.py", line 85, in deal_timeTask
    self.get_timeTaskList(content, e_context)
  File "E:\chatgpt-on-wechat-master-2\plugins\timetask\timetask.py", line 126, in get_timeTaskList
    taskArray = ExcelTool().readExcel()
  File "E:\chatgpt-on-wechat-master-2\plugins\timetask\Tool.py", line 112, in readExcel
    wb = load_workbook(workbook_file_path)
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\site-packages\openpyxl\reader\excel.py", line 344, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\site-packages\openpyxl\reader\excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\site-packages\openpyxl\reader\excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1361, in _RealGetContents
    raise BadZipFile("Bad magic number for central directory")

重新加载插件后显示同一个错误：
[timetask] inited
[INFO][2023-12-03 10:35:34][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
插件配置已重载), receiver=@XXXX
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "E:\chatgpt-on-wechat-master-2\plugins\timetask\TimeTaskTool.py", line 60, in pingTimeTask_in_sub_thread
    obj.create_excel()
  File "E:\chatgpt-on-wechat-master-2\plugins\timetask\Tool.py", line 96, in create_excel
    wb = load_workbook(workbook_file_path)
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\site-packages\openpyxl\reader\excel.py", line 344, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\site-packages\openpyxl\reader\excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\site-packages\openpyxl\reader\excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "C:\Users\gh\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1361, in _RealGetContents
    raise BadZipFile("Bad magic number for central directory")
zipfile.BadZipFile: Bad magic number for central directory

**Comment by haikerapples** [comment]
看起来日志都在Python环境内部报的，感觉Python出问题了，重装一下Python试试
