### ISSUE TITLE
<@bot $time 明天 08:30 点歌 刘德华>该命令点歌失败

### ISSUE THREAD

**Issue by PrettyTao9527** [haikerapples/timetask#9]
首先：timetask插件正常安装，并且早报、搜索、提醒、GPT等功能都正常，唯独点歌任务建立是没问题，但是到点之后没有歌曲播放，且报错如下：未知插件命令   查看插件命令列表请输入#help 插件名。

**Comment by PrettyTao9527** [comment]
有哪位大佬知道怎么解决点歌功能吗？求指导

**Comment by LSliu666** [comment]
需要下载安装相应插件，插件地址：https://github.com/nautilis/plugin_music

**Comment by markgeen** [comment]
> 需要下载安装相应插件，插件地址：https://github.com/nautilis/plugin_music

这个plugin_music插件执行一直报错：[INFO][2023-12-03 18:38:18][netease_music.py:42] - content => music 点歌:可惜我是水瓶座-杨千嬅
可惜我是水瓶座
杨千嬅
200
ERROR:root:search song buss code:50000005, resp:{'code': 50000005}
[ERROR][2023-12-03 18:38:19][chat_channel.py:299] - Worker return exception: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\1614879355\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\channel\chat_channel.py", line 168, in _handle
    reply = self._generate_reply(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\channel\chat_channel.py", line 178, in _generate_reply
    e_context = PluginManager().emit_event(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_music\netease_music.py", line 52, in on_handle_context
    url, name, ar = self.search_song(msg)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_music\netease_music.py", line 99, in search_song
    if resp["code"] == 200:
       ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable不知道为啥。用singsong+网易云api成功点歌了。

**Comment by couurh** [comment]
> > 需要下载安装相应插件，插件地址：https://github.com/nautilis/plugin_music
> 
> 这个plugin_music插件执行一直报错：[INFO][2023-12-03 18:38:18][netease_music.py:42] - content => 音乐点歌: 可惜我是水瓶座-杨千嬅 可惜我是水瓶座 杨千嬅 200 ERROR：root：搜索歌曲总线代码：50000005，resp：{'code'：50000005} [错误][2023-12-03 18:38:19][chat_channel.py:299] - Worker返回异常：'NoneType ' 对象不可下 标回溯（最近一次调用最后一次）： 文件“C:\Users\1614879355\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py”，第 58 行，运行 结果= self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件“C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\channel\chat_channel.py”，第 168 行，在 _handle 回复 = self._generate_reply(context) ^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^ 文件“C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\channel\chat_channel.py”，第 178 行，在 _generate_reply 中 e_context = PluginManager().emit_event( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件 "C:\Users\1614879355\Desktop\python work\chatgpt -on-wechat\plugins\plugin_manager.py”，第189行，在emit_event 实例中。handlers[e_context.event](e_context, *args, **kwargs) 文件“C:\Users\1614879355\Desktop\python work\chatgpt -on-wechat\plugins\plugin_music\netease_music.py"，第52行，on_handle_context url中，名称，ar = self.search_song(msg) ^^^^^^^^^^^^^^^^^^^^ ^^ 文件 "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_music\netease_music.py"，第 99 行，在 search_song if resp["code"] == 200: ~~~ ~^^^^^^^^ TypeError: 'NoneType' object is not subscriptable不知道为啥。用singsong+网易云api成功点歌了。

解决了吗

**Comment by sakiyumemori** [comment]
> > 需要下载安装相应插件，插件地址：https://github.com/nautilis/plugin_music
> 
> 这个plugin_music插件执行一直报错：[INFO][2023-12-03 18:38:18][netease_music.py:42] - content => music 点歌:可惜我是水瓶座-杨千嬅 可惜我是水瓶座 杨千嬅 200 ERROR:root:search song buss code:50000005, resp:{'code': 50000005} [ERROR][2023-12-03 18:38:19][chat_channel.py:299] - Worker return exception: 'NoneType' object is not subscriptable Traceback (most recent call last): File "C:\Users\1614879355\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\channel\chat_channel.py", line 168, in _handle reply = self._generate_reply(context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\channel\chat_channel.py", line 178, in _generate_reply e_context = PluginManager().emit_event( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_manager.py", line 189, in emit_event instance.handlers[e_context.event](e_context, *args, **kwargs) File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_music\netease_music.py", line 52, in on_handle_context url, name, ar = self.search_song(msg) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\1614879355\Desktop\python work\chatgpt-on-wechat\plugins\plugin_music\netease_music.py", line 99, in search_song if resp["code"] == 200: ~~~~^^^^^^^^ TypeError: 'NoneType' object is not subscriptable不知道为啥。用singsong+网易云api成功点歌了。

config.json中的passwd需要md5 32位小写加密后填入
